services:
  - type: web
    name: piticas-ponto
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATA_DIR
        value: /opt/render/project/data
      - key: PYTHON_VERSION
        value: 3.13.2
    disk:
      name: ponto-data
      mountPath: /opt/render/project/data
      sizeGB: 1
